report_to: "['mlflow', 'tensorboard']"
logging_dir: None
output_dir: None
eval_batch_size: 8
train_batch_size: 8
per_gpu_eval_batch_size: 8
per_gpu_train_batch_size: 8
sharded_ddp: '[]'
skip_memory_metrics: true
tf32: None
torchdynamo: None
optim_args: None
hub_token: <HUB_TOKEN>
label_names: None
data_seed: None
fp16: false
fp16_backend: auto
fp16_full_eval: false
fp16_opt_level: O1
fsdp: '[]'
fsdp_min_num_params: 0
fsdp_transformer_layer_cls_to_wrap: None
full_determinism: false
ddp_bucket_cap_mb: None
ddp_find_unused_parameters: None
ddp_timeout: 1800
debug: '[]'
deepspeed: None
eval_delay: 0
push_to_hub_token: <PUSH_TO_HUB_TOKEN>
push_to_hub_model_id: None
push_to_hub_organization: None
run_name: ""